openapi: 3.0.0
info:
  title: Store Manager Rest API
  description: Endpoints documentation for Store Manager Rest API
  version: 1.0.0
paths:
  /stores:
    get:
      $ref: '#/components/routes/stores/GetAll'
    post:
      $ref: '#/components/routes/stores/Add'
  /stores/{storeId}:
    get:
      $ref: '#/components/routes/stores/GetOne'
    delete:
      $ref: '#/components/routes/stores/DeleteOne'
    patch:
      $ref: '#/components/routes/stores/EditOne'
  /stores/{storeId}/products:
    get:
      $ref: '#/components/routes/stores/GetStoreProducts'
    post:
      $ref: '#/components/routes/stores/AddProductToStore'
  /stores/{storeId}/products/{productId}:
    delete:
      $ref: '#/components/routes/stores/DeleteStoreProduct'
  /products:
    get:
      $ref: '#/components/routes/products/GetAll'
  /products/{productId}:
    get:
      $ref: '#/components/routes/products/GetOne'
    delete:
      $ref: '#/components/routes/products/DeleteOne'
    patch:
      $ref: '#/components/routes/products/EditOne'
  /products/{productId}/reviews:
    get:
      $ref: '#/components/routes/reviews/GetProductReviews'
  /reviews:
    get:
      $ref: '#/components/routes/reviews/GetAll'
    post:
      $ref: '#/components/routes/reviews/Add'
  /reviews/{reviewId}:
    get:
      $ref: '#/components/routes/reviews/GetOne'
    delete:
      $ref: '#/components/routes/reviews/DeleteOne'
    patch:
      $ref: '#/components/routes/reviews/EditOne'
  /orders:
    get:
      $ref: '#/components/routes/orders/GetAll'
    post:
      $ref: '#/components/routes/orders/Add'
  /orders/{orderId}:
    get:
      $ref: '#/components/routes/orders/GetOne'
    patch:
      $ref: '#/components/routes/orders/EditOne'
    delete:
      $ref: '#/components/routes/orders/DeleteOne'
