export enum HTTP_STATUS_CODES {
  BAD_REQUEST = 400,
  FORBIDEN = 403,
  UNAUTHORIZED = 401,
  NOT_FOUND = 404,
  DUPLICATED_RESOURCE = 409,
  STH_WENT_WRONG = 500,
  CREATED = 201,
  OK = 200,
}

export enum ORDER_STATUS {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
}
