#!/bin/bash

URL="http://localhost:8000/users"
REQUEST_NUMBER=10000
REQUESTS_PER_SECONDS=500
CONCURENCY=500
TOKEN="Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkJlYXJlciJ9.eyJlbWFpbCI6Imp1bGllbitsb2FkQG1haWwuY29tIiwiaWF0IjoxNzMxMDI1MzkwLCJleHAiOjE3MzEwMjcxOTAsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMCIsInN1YiI6IjY3MmQ1NTUyNWNmZDFiODg0ZDBlYjBjMiIsImp0aSI6ImE4Y2ZiOTNkLWQ4YjctNGE5Ny04NTZmLWYwMzBhZmM5MGFlOCJ9._mFw2ZpcQvSMpUGSPfRJ1SFM-zrhtgYSzuuGI62yXbM"

loadtest --cores 1 -n ${REQUEST_NUMBER} -c ${CONCURENCY} --rps ${REQUESTS_PER_SECONDS} -k ${URL} -H "Authorization:${TOKEN}"