#!/bin/bash

URL="http://localhost:8000/v1/users"
REQUEST_NUMBER=10000
REQUESTS_PER_SECONDS=500
CONCURENCY=500
TOKEN="Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkJlYXJlciJ9.eyJlbWFpbCI6Imp1bGllbkBtYWlsLmNvbSIsImlhdCI6MTczMTI2MjE2OCwiZXhwIjoxNzMxMjYzOTY4LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAiLCJzdWIiOiI2NzJkNTU1MjVjZmQxYjg4NGQwZWIwYzQiLCJqdGkiOiJlNjliNGM0OC04YjE4LTRmYTgtOWQzOS1mMzE1MjE4NzYyMTgifQ.hn0LnO8L0DrinaJLSmr6RFPnXNNGz9kgbERirQjSIME"

loadtest --cores 1 -n ${REQUEST_NUMBER} -c ${CONCURENCY} --rps ${REQUESTS_PER_SECONDS} -k ${URL} -H "Authorization:${TOKEN}"